name: package and deploy

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Jar version
      
jobs:    
  build-artifact:
    name: "build artifact"
    runs-on: "ubuntu-latest"  
    
    permissions:
      contents: read
      packages: write
      deployments: write
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: pack
      run: |
        mvn package
      env:
         S_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         USERNAME: ${{ github.actor }}
    - name: ls
      run: ls -lthra target
    - name: deploy maven to package
      run: |        
        mvn deploy:deploy-file -DgroupId=org.snsinahub \
        -DartifactId=webapp2 \
        -Dversion=${{ inputs.version }} \
        -Dpackaging=jar \
        -Dfile=target/web-app-1.1.1-SNAPSHOT.jar \
        -DrepositoryId=github \
        -Durl=https://maven.pkg.github.com/${{ github.repository }}
      env:
         S_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         USERNAME: ${{ github.actor }}
         